# Generated by Django 3.2 on 2022-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_supremeuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supremeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
