# Generated by Django 3.2 on 2022-08-14 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_supremeuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supremeuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
