# Generated by Django 3.2 on 2022-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20220814_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='supremeuser',
            name='bio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
