export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'


export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST'
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'
export const POST_DETAIL_FAIL = 'POST_DETAIL_FAIL'



export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'


export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'

export const OTHER_USERS_POSTS_REQUEST = 'OTHER_USERS_POSTS_REQUEST'
export const OTHER_USERS_POSTS_SUCCESS = 'OTHER_USERS_POSTS_SUCCESS'
export const OTHER_USERS_POSTS_FAIL = 'OTHER_USERS_POSTS_FAIL'


export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const CREATE_LIKE_FAIL = 'CREATE_LIKE_FAIL'

export const GET_LIKE_REQUEST = 'GET_LIKE_REQUEST'
export const GET_LIKE_SUCCESS = 'GET_LIKE_SUCCESS'
export const GET_LIKE_FAIL = 'GET_LIKE_FAIL'


