export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'


export const USER_LOGOUT = 'USER_LOGIN_OUT'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'


export const OTHER_USERS_DETAIL_REQUEST = 'OTHER_USERS_DETAILS_REQUEST'
export const OTHER_USERS_DETAIL_SUCCESS = 'OTHER_USERS_DETAILS_SUCCESS'
export const OTHER_USERS_DETAIL_FAIL = 'OTHER_USERS_DETAIL_FAIL'


export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS '
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'

export const GETUSER_FOLLOWERS_REQUEST = 'GETUSER_FOLLOWERS_REQUEST'
export const GETUSER_FOLLOWERS_SUCCESS = 'GETUSER_FOLLOWERS_SUCCESS'
export const GETUSER_FOLLOWERS_FAIL = 'GUETUSER_FOLLOWERS_FAIL'