# Generated by Django 3.2 on 2022-08-27 00:05

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=Posts.models.post_image_upload_path),
        ),
    ]
